import type { InteractivePaper, PastQuestion } from "../../core/types/passPaper";

// ---------------------------------------------------------------------------
// Helper – generate stable IDs
// ---------------------------------------------------------------------------
const qid = (subject: string, year: number, paper: number, index: number) =>
  `${subject}-${year}-p${paper}-q${index + 1}`;

// ---------------------------------------------------------------------------
// MATHEMATICS  2022  Paper 1 (Objective)
// ---------------------------------------------------------------------------
const math2022P1: PastQuestion[] = [
  {
    id: qid("math", 2022, 1, 0),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Number Bases",
    question: "Convert 101101₂ to base 10.",
    options: ["45", "44", "43", "46"],
    correctIndex: 0,
    explanation: "101101₂ = 1×32 + 0×16 + 1×8 + 1×4 + 0×2 + 1×1 = 32 + 8 + 4 + 1 = 45.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 1),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Algebra",
    question: "Simplify: 3(2x − 5) − 2(x − 3).",
    options: ["4x − 9", "4x − 21", "4x + 9", "8x − 9"],
    correctIndex: 0,
    explanation: "3(2x − 5) − 2(x − 3) = 6x − 15 − 2x + 6 = 4x − 9.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 2),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Indices",
    question: "Evaluate 27^(2/3).",
    options: ["9", "3", "18", "6"],
    correctIndex: 0,
    explanation: "27^(2/3) = (∛27)² = 3² = 9.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 3),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Logarithms",
    question: "If log₁₀ 2 = 0.3010, find log₁₀ 8.",
    options: ["0.9030", "0.6020", "2.4080", "0.3010"],
    correctIndex: 0,
    explanation: "log₁₀ 8 = log₁₀ 2³ = 3 × log₁₀ 2 = 3 × 0.3010 = 0.9030.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2022, 1, 4),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Sets",
    question: "In a class of 40 students, 25 offer Mathematics and 20 offer Chemistry. If 5 students offer neither, how many offer both?",
    options: ["10", "15", "5", "20"],
    correctIndex: 0,
    explanation: "Students offering at least one = 40 − 5 = 35. Both = 25 + 20 − 35 = 10.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2022, 1, 5),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Quadratic Equations",
    question: "Find the roots of x² − 5x + 6 = 0.",
    options: ["x = 2 and x = 3", "x = −2 and x = −3", "x = 1 and x = 6", "x = −1 and x = −6"],
    correctIndex: 0,
    explanation: "x² − 5x + 6 = (x − 2)(x − 3) = 0, so x = 2 or x = 3.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 6),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Mensuration",
    question: "Find the area of a circle with radius 7 cm. (Take π = 22/7)",
    options: ["154 cm²", "44 cm²", "22 cm²", "308 cm²"],
    correctIndex: 0,
    explanation: "Area = πr² = (22/7) × 7² = (22/7) × 49 = 154 cm².",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 7),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Trigonometry",
    question: "In a right-angled triangle, if the opposite side is 5 and the hypotenuse is 13, what is sin θ?",
    options: ["5/13", "12/13", "5/12", "13/5"],
    correctIndex: 0,
    explanation: "sin θ = opposite / hypotenuse = 5/13.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 8),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Statistics",
    question: "Find the mean of the numbers: 3, 7, 5, 9, 6.",
    options: ["6", "5", "7", "8"],
    correctIndex: 0,
    explanation: "Mean = (3 + 7 + 5 + 9 + 6) / 5 = 30 / 5 = 6.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 9),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Probability",
    question: "A bag contains 3 red and 5 blue balls. What is the probability of picking a red ball at random?",
    options: ["3/8", "5/8", "3/5", "1/3"],
    correctIndex: 0,
    explanation: "P(red) = number of red balls / total balls = 3 / 8.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 10),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Sequences",
    question: "Find the 10th term of the arithmetic progression: 2, 5, 8, 11, …",
    options: ["29", "32", "26", "30"],
    correctIndex: 0,
    explanation: "a = 2, d = 3. T₁₀ = a + (n−1)d = 2 + 9(3) = 29.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2022, 1, 11),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Matrices",
    question: "If A = [[2, 3], [1, 4]], find the determinant of A.",
    options: ["5", "11", "8", "−5"],
    correctIndex: 0,
    explanation: "det(A) = (2)(4) − (3)(1) = 8 − 3 = 5.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2022, 1, 12),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Variation",
    question: "If y varies directly as x and y = 12 when x = 4, find y when x = 7.",
    options: ["21", "28", "16", "9"],
    correctIndex: 0,
    explanation: "y = kx → 12 = 4k → k = 3. When x = 7, y = 3 × 7 = 21.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2022, 1, 13),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Coordinate Geometry",
    question: "Find the distance between the points (1, 2) and (4, 6).",
    options: ["5", "7", "3", "25"],
    correctIndex: 0,
    explanation: "d = √[(4−1)² + (6−2)²] = √[9 + 16] = √25 = 5.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2022, 1, 14),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Inequalities",
    question: "Solve the inequality: 3x − 7 < 2x + 5.",
    options: ["x < 12", "x > 12", "x < −12", "x > −2"],
    correctIndex: 0,
    explanation: "3x − 7 < 2x + 5 → 3x − 2x < 5 + 7 → x < 12.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 15),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Surds",
    question: "Simplify √50.",
    options: ["5√2", "2√5", "25√2", "10√5"],
    correctIndex: 0,
    explanation: "√50 = √(25 × 2) = 5√2.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 16),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Percentages",
    question: "A trader bought an article for GH₵200 and sold it for GH₵250. Find the percentage profit.",
    options: ["25%", "20%", "50%", "12.5%"],
    correctIndex: 0,
    explanation: "Profit = 250 − 200 = 50. % profit = (50/200) × 100 = 25%.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2022, 1, 17),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Geometry",
    question: "The sum of interior angles of a regular polygon is 720°. How many sides does it have?",
    options: ["6", "5", "8", "7"],
    correctIndex: 0,
    explanation: "(n − 2) × 180 = 720 → n − 2 = 4 → n = 6.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2022, 1, 18),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Simultaneous Equations",
    question: "Solve: 2x + y = 7 and x − y = 2.",
    options: ["x = 3, y = 1", "x = 2, y = 3", "x = 1, y = 5", "x = 4, y = −1"],
    correctIndex: 0,
    explanation: "Adding both equations: 3x = 9 → x = 3. Substituting: y = 7 − 6 = 1.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2022, 1, 19),
    subject: "math",
    year: 2022,
    paper: 1,
    topic: "Fractions",
    question: "Simplify: (3/4) ÷ (1/2).",
    options: ["3/2", "3/8", "2/3", "1/2"],
    correctIndex: 0,
    explanation: "(3/4) ÷ (1/2) = (3/4) × (2/1) = 6/4 = 3/2.",
    difficulty: "easy",
  },
];

// ---------------------------------------------------------------------------
// PHYSICS  2022  Paper 1 (Objective)
// ---------------------------------------------------------------------------
const physics2022P1: PastQuestion[] = [
  {
    id: qid("physics", 2022, 1, 0),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Measurements",
    question: "Which of the following is a fundamental quantity?",
    options: ["Mass", "Velocity", "Force", "Pressure"],
    correctIndex: 0,
    explanation: "Mass is a fundamental (base) quantity in the SI system. Velocity, force, and pressure are derived quantities.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 1),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Motion",
    question: "A car starts from rest and accelerates uniformly at 5 m/s². Find its velocity after 4 seconds.",
    options: ["20 m/s", "25 m/s", "10 m/s", "40 m/s"],
    correctIndex: 0,
    explanation: "v = u + at = 0 + 5 × 4 = 20 m/s.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 2),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Newton's Laws",
    question: "A body of mass 10 kg is acted upon by a net force of 50 N. What is its acceleration?",
    options: ["5 m/s²", "500 m/s²", "0.2 m/s²", "60 m/s²"],
    correctIndex: 0,
    explanation: "F = ma → a = F/m = 50/10 = 5 m/s².",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 3),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Energy",
    question: "A ball of mass 2 kg is thrown vertically upward with a velocity of 10 m/s. What is its kinetic energy at the point of release?",
    options: ["100 J", "200 J", "50 J", "20 J"],
    correctIndex: 0,
    explanation: "KE = ½mv² = ½ × 2 × 10² = 100 J.",
    difficulty: "medium",
  },
  {
    id: qid("physics", 2022, 1, 4),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Waves",
    question: "A wave has a frequency of 50 Hz and a wavelength of 4 m. What is its speed?",
    options: ["200 m/s", "12.5 m/s", "54 m/s", "46 m/s"],
    correctIndex: 0,
    explanation: "v = fλ = 50 × 4 = 200 m/s.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 5),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Electricity",
    question: "A 12 V battery is connected across a 4 Ω resistor. What current flows through the circuit?",
    options: ["3 A", "48 A", "0.33 A", "8 A"],
    correctIndex: 0,
    explanation: "I = V/R = 12/4 = 3 A (Ohm's law).",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 6),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Heat",
    question: "The specific heat capacity of water is 4200 J/kg°C. How much heat is required to raise the temperature of 0.5 kg of water by 20°C?",
    options: ["42,000 J", "4,200 J", "84,000 J", "21,000 J"],
    correctIndex: 0,
    explanation: "Q = mcΔθ = 0.5 × 4200 × 20 = 42,000 J.",
    difficulty: "medium",
  },
  {
    id: qid("physics", 2022, 1, 7),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Light",
    question: "The angle of incidence equals the angle of reflection. This is the law of:",
    options: ["Reflection", "Refraction", "Diffraction", "Polarisation"],
    correctIndex: 0,
    explanation: "The first law of reflection states that the angle of incidence equals the angle of reflection.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 8),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Pressure",
    question: "Calculate the pressure exerted by a force of 200 N on an area of 0.5 m².",
    options: ["400 Pa", "100 Pa", "200 Pa", "0.0025 Pa"],
    correctIndex: 0,
    explanation: "P = F/A = 200/0.5 = 400 Pa.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 9),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Gravitational Field",
    question: "An object weighs 60 N on Earth where g = 10 m/s². What is its mass?",
    options: ["6 kg", "60 kg", "600 kg", "0.6 kg"],
    correctIndex: 0,
    explanation: "W = mg → m = W/g = 60/10 = 6 kg.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 10),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Momentum",
    question: "A 5 kg body moving at 8 m/s collides with a stationary 3 kg body. If they stick together, what is their common velocity?",
    options: ["5 m/s", "8 m/s", "3 m/s", "40 m/s"],
    correctIndex: 0,
    explanation: "By conservation of momentum: 5×8 + 3×0 = (5+3)v → 40 = 8v → v = 5 m/s.",
    difficulty: "medium",
  },
  {
    id: qid("physics", 2022, 1, 11),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Electromagnetic Induction",
    question: "Faraday's law states that the induced EMF in a coil is proportional to the rate of change of:",
    options: ["Magnetic flux", "Electric current", "Resistance", "Capacitance"],
    correctIndex: 0,
    explanation: "Faraday's law: the induced EMF is proportional to the rate of change of magnetic flux linkage through the circuit.",
    difficulty: "medium",
  },
  {
    id: qid("physics", 2022, 1, 12),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Nuclear Physics",
    question: "In beta-minus decay, a neutron transforms into a proton and emits:",
    options: ["An electron and an antineutrino", "A positron and a neutrino", "An alpha particle", "A gamma ray"],
    correctIndex: 0,
    explanation: "In β⁻ decay, a neutron → proton + electron (β⁻ particle) + electron antineutrino.",
    difficulty: "hard",
  },
  {
    id: qid("physics", 2022, 1, 13),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Simple Machines",
    question: "A lever has an effort arm of 2 m and a load arm of 0.5 m. What is its mechanical advantage?",
    options: ["4", "2.5", "1", "0.25"],
    correctIndex: 0,
    explanation: "MA = effort arm / load arm = 2 / 0.5 = 4.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 14),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Sound",
    question: "The speed of sound is greatest in:",
    options: ["Solids", "Liquids", "Gases", "Vacuum"],
    correctIndex: 0,
    explanation: "Sound travels fastest in solids because molecules are closest together, allowing vibrations to be transmitted quickly.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 15),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Electricity",
    question: "Three resistors of 2 Ω, 3 Ω, and 6 Ω are connected in parallel. What is the equivalent resistance?",
    options: ["1 Ω", "11 Ω", "0.5 Ω", "6 Ω"],
    correctIndex: 0,
    explanation: "1/R = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 6/6 = 1. So R = 1 Ω.",
    difficulty: "medium",
  },
  {
    id: qid("physics", 2022, 1, 16),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Projectile Motion",
    question: "A ball is projected horizontally from a cliff 80 m high. How long does it take to reach the ground? (g = 10 m/s²)",
    options: ["4 s", "8 s", "2 s", "16 s"],
    correctIndex: 0,
    explanation: "h = ½gt² → 80 = ½ × 10 × t² → t² = 16 → t = 4 s.",
    difficulty: "medium",
  },
  {
    id: qid("physics", 2022, 1, 17),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Work and Power",
    question: "A machine does 3000 J of work in 10 seconds. What is its power output?",
    options: ["300 W", "3000 W", "30 W", "30,000 W"],
    correctIndex: 0,
    explanation: "Power = Work / Time = 3000 / 10 = 300 W.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 18),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Density",
    question: "A block of wood has a mass of 600 g and a volume of 750 cm³. What is its density?",
    options: ["0.8 g/cm³", "1.25 g/cm³", "450 g/cm³", "0.08 g/cm³"],
    correctIndex: 0,
    explanation: "Density = mass/volume = 600/750 = 0.8 g/cm³.",
    difficulty: "easy",
  },
  {
    id: qid("physics", 2022, 1, 19),
    subject: "physics",
    year: 2022,
    paper: 1,
    topic: "Electrostatics",
    question: "Two like charges are brought close together. They will:",
    options: ["Repel each other", "Attract each other", "Have no effect", "Neutralize each other"],
    correctIndex: 0,
    explanation: "Like charges repel each other; unlike charges attract.",
    difficulty: "easy",
  },
];

// ---------------------------------------------------------------------------
// CHEMISTRY  2022  Paper 1 (Objective)
// ---------------------------------------------------------------------------
const chemistry2022P1: PastQuestion[] = [
  {
    id: qid("chemistry", 2022, 1, 0),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Atomic Structure",
    question: "An atom with atomic number 11 and mass number 23 has how many neutrons?",
    options: ["12", "11", "23", "34"],
    correctIndex: 0,
    explanation: "Neutrons = mass number − atomic number = 23 − 11 = 12.",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 1),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Periodic Table",
    question: "Elements in the same group of the periodic table have the same number of:",
    options: ["Valence electrons", "Neutrons", "Protons", "Total electrons"],
    correctIndex: 0,
    explanation: "Elements in the same group have the same number of valence (outer shell) electrons, which gives them similar chemical properties.",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 2),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Chemical Bonding",
    question: "Which type of bond is formed when electrons are shared between two non-metal atoms?",
    options: ["Covalent bond", "Ionic bond", "Metallic bond", "Hydrogen bond"],
    correctIndex: 0,
    explanation: "A covalent bond is formed when two non-metal atoms share electrons to achieve stable electron configurations.",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 3),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Stoichiometry",
    question: "What is the molar mass of H₂SO₄? (H = 1, S = 32, O = 16)",
    options: ["98 g/mol", "96 g/mol", "64 g/mol", "100 g/mol"],
    correctIndex: 0,
    explanation: "M(H₂SO₄) = 2(1) + 32 + 4(16) = 2 + 32 + 64 = 98 g/mol.",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 4),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Gas Laws",
    question: "At constant temperature, when the volume of a gas is halved, the pressure:",
    options: ["Doubles", "Halves", "Remains the same", "Quadruples"],
    correctIndex: 0,
    explanation: "Boyle's Law: PV = constant. If V is halved, P must double.",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 5),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Acids and Bases",
    question: "What is the pH of a 0.01 M HCl solution?",
    options: ["2", "1", "0.01", "12"],
    correctIndex: 0,
    explanation: "HCl is a strong acid, fully dissociated. [H⁺] = 0.01 M. pH = −log(0.01) = 2.",
    difficulty: "medium",
  },
  {
    id: qid("chemistry", 2022, 1, 6),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Redox Reactions",
    question: "In the reaction: Zn + CuSO₄ → ZnSO₄ + Cu, the substance oxidised is:",
    options: ["Zn", "Cu", "CuSO₄", "ZnSO₄"],
    correctIndex: 0,
    explanation: "Zinc loses electrons (Zn → Zn²⁺ + 2e⁻), so it is oxidised. Copper ions are reduced.",
    difficulty: "medium",
  },
  {
    id: qid("chemistry", 2022, 1, 7),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Organic Chemistry",
    question: "The general formula for alkanes is:",
    options: ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙHₙ"],
    correctIndex: 0,
    explanation: "Alkanes are saturated hydrocarbons with single bonds only. Their general formula is CₙH₂ₙ₊₂.",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 8),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Electrolysis",
    question: "During the electrolysis of brine (concentrated NaCl solution), the gas produced at the anode is:",
    options: ["Chlorine", "Hydrogen", "Oxygen", "Sodium"],
    correctIndex: 0,
    explanation: "At the anode, chloride ions are oxidised: 2Cl⁻ → Cl₂ + 2e⁻. Chlorine gas is produced.",
    difficulty: "medium",
  },
  {
    id: qid("chemistry", 2022, 1, 9),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Rates of Reaction",
    question: "Which of the following would increase the rate of a chemical reaction?",
    options: ["Increasing the temperature", "Decreasing the concentration of reactants", "Using larger particles", "Reducing the pressure"],
    correctIndex: 0,
    explanation: "Increasing temperature provides more kinetic energy to molecules, leading to more frequent and energetic collisions.",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 10),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Water",
    question: "Temporary hardness of water is caused by the presence of:",
    options: ["Calcium hydrogencarbonate", "Calcium sulphate", "Sodium chloride", "Magnesium sulphate"],
    correctIndex: 0,
    explanation: "Temporary hardness is caused by dissolved calcium or magnesium hydrogencarbonates, removable by boiling.",
    difficulty: "medium",
  },
  {
    id: qid("chemistry", 2022, 1, 11),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Metals",
    question: "Which metal is extracted from its ore by electrolysis because it is too reactive to be reduced by carbon?",
    options: ["Aluminium", "Iron", "Copper", "Lead"],
    correctIndex: 0,
    explanation: "Aluminium is too high in the reactivity series to be reduced by carbon. It is extracted from bauxite by electrolysis.",
    difficulty: "medium",
  },
  {
    id: qid("chemistry", 2022, 1, 12),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Chemical Equilibrium",
    question: "In a reversible reaction at equilibrium, which statement is true?",
    options: [
      "The rates of forward and reverse reactions are equal",
      "All reactants have been converted to products",
      "The forward reaction has stopped",
      "Only the reverse reaction occurs",
    ],
    correctIndex: 0,
    explanation: "At equilibrium, the rates of the forward and reverse reactions are equal, so concentrations remain constant.",
    difficulty: "medium",
  },
  {
    id: qid("chemistry", 2022, 1, 13),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Environmental Chemistry",
    question: "Acid rain is primarily caused by the emission of:",
    options: ["SO₂ and NO₂", "CO₂ and H₂O", "O₃ and N₂", "CH₄ and CO"],
    correctIndex: 0,
    explanation: "Sulphur dioxide (SO₂) and nitrogen dioxide (NO₂) dissolve in rainwater to form sulphuric and nitric acids.",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 14),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Organic Chemistry",
    question: "Ethanol can be converted to ethanoic acid by:",
    options: ["Oxidation", "Reduction", "Hydrolysis", "Polymerisation"],
    correctIndex: 0,
    explanation: "Ethanol (C₂H₅OH) is oxidised to ethanoic acid (CH₃COOH) using acidified potassium dichromate.",
    difficulty: "medium",
  },
  {
    id: qid("chemistry", 2022, 1, 15),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "States of Matter",
    question: "The process by which a solid changes directly to a gas without passing through the liquid state is called:",
    options: ["Sublimation", "Evaporation", "Condensation", "Diffusion"],
    correctIndex: 0,
    explanation: "Sublimation is the direct phase change from solid to gas (e.g., dry ice, iodine crystals).",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 16),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Atomic Structure",
    question: "Isotopes of an element differ in the number of:",
    options: ["Neutrons", "Protons", "Electrons", "Valence electrons"],
    correctIndex: 0,
    explanation: "Isotopes have the same atomic number (same protons) but different mass numbers (different neutrons).",
    difficulty: "easy",
  },
  {
    id: qid("chemistry", 2022, 1, 17),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Salts",
    question: "Which of the following salts is insoluble in water?",
    options: ["BaSO₄", "NaCl", "KNO₃", "Na₂SO₄"],
    correctIndex: 0,
    explanation: "Barium sulphate (BaSO₄) is insoluble in water. Most sulphates are soluble except those of Ba, Pb, and Ca.",
    difficulty: "medium",
  },
  {
    id: qid("chemistry", 2022, 1, 18),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Chemical Bonding",
    question: "The shape of a methane (CH₄) molecule is:",
    options: ["Tetrahedral", "Linear", "Trigonal planar", "Octahedral"],
    correctIndex: 0,
    explanation: "Methane has 4 bonding pairs around the central carbon atom, giving it a tetrahedral shape with bond angles of 109.5°.",
    difficulty: "medium",
  },
  {
    id: qid("chemistry", 2022, 1, 19),
    subject: "chemistry",
    year: 2022,
    paper: 1,
    topic: "Energy Changes",
    question: "A reaction that absorbs heat from the surroundings is called:",
    options: ["Endothermic", "Exothermic", "Isothermal", "Adiabatic"],
    correctIndex: 0,
    explanation: "An endothermic reaction absorbs heat energy from the surroundings, causing the surroundings to cool.",
    difficulty: "easy",
  },
];

// ---------------------------------------------------------------------------
// BIOLOGY  2022  Paper 1 (Objective)
// ---------------------------------------------------------------------------
const biology2022P1: PastQuestion[] = [
  {
    id: qid("biology", 2022, 1, 0),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Cell Biology",
    question: "Which organelle is responsible for protein synthesis?",
    options: ["Ribosome", "Mitochondrion", "Golgi body", "Lysosome"],
    correctIndex: 0,
    explanation: "Ribosomes are the site of protein synthesis where mRNA is translated into polypeptide chains.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 1),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Cell Biology",
    question: "Which of the following is found in plant cells but NOT in animal cells?",
    options: ["Cell wall", "Cell membrane", "Nucleus", "Mitochondria"],
    correctIndex: 0,
    explanation: "Plant cells have a rigid cell wall made of cellulose outside the cell membrane. Animal cells lack a cell wall.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 2),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Nutrition",
    question: "Photosynthesis takes place primarily in the:",
    options: ["Leaves", "Roots", "Stem", "Flowers"],
    correctIndex: 0,
    explanation: "Photosynthesis occurs mainly in leaves, which contain chloroplasts with chlorophyll for capturing light energy.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 3),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Respiration",
    question: "The chemical equation for aerobic respiration is:",
    options: [
      "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Energy",
      "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂",
      "C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂",
      "2H₂ + O₂ → 2H₂O",
    ],
    correctIndex: 0,
    explanation: "Aerobic respiration breaks down glucose using oxygen to produce carbon dioxide, water, and ATP energy.",
    difficulty: "medium",
  },
  {
    id: qid("biology", 2022, 1, 4),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Genetics",
    question: "If both parents are heterozygous (Aa) for a trait, what percentage of offspring would be homozygous recessive?",
    options: ["25%", "50%", "75%", "100%"],
    correctIndex: 0,
    explanation: "Aa × Aa cross gives: AA (25%), Aa (25%), Aa (25%), aa (25%). Homozygous recessive (aa) = 25%.",
    difficulty: "medium",
  },
  {
    id: qid("biology", 2022, 1, 5),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Ecology",
    question: "In a food chain, organisms that feed on producers are called:",
    options: ["Primary consumers", "Secondary consumers", "Decomposers", "Tertiary consumers"],
    correctIndex: 0,
    explanation: "Primary consumers (herbivores) feed directly on producers (green plants) in a food chain.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 6),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Transport",
    question: "The main function of red blood cells is to:",
    options: ["Transport oxygen", "Fight infections", "Clot blood", "Transport hormones"],
    correctIndex: 0,
    explanation: "Red blood cells contain haemoglobin, which binds with oxygen to form oxyhaemoglobin for transport around the body.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 7),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Excretion",
    question: "The main organ of excretion in humans is the:",
    options: ["Kidney", "Liver", "Lung", "Skin"],
    correctIndex: 0,
    explanation: "The kidneys are the main excretory organs, removing urea, excess water, and salts from the blood as urine.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 8),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Reproduction",
    question: "Fertilisation in humans takes place in the:",
    options: ["Fallopian tube (oviduct)", "Uterus", "Ovary", "Vagina"],
    correctIndex: 0,
    explanation: "Fertilisation typically occurs in the fallopian tube (oviduct), where the sperm meets and fuses with the ovum.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 9),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Evolution",
    question: "The theory of evolution by natural selection was proposed by:",
    options: ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Robert Hooke"],
    correctIndex: 0,
    explanation: "Charles Darwin proposed the theory of evolution by natural selection in 'On the Origin of Species' (1859).",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 10),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Enzymes",
    question: "Enzymes are biological catalysts made of:",
    options: ["Proteins", "Carbohydrates", "Lipids", "Nucleic acids"],
    correctIndex: 0,
    explanation: "Enzymes are globular proteins that catalyse biochemical reactions by lowering activation energy.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 11),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Osmosis",
    question: "When a plant cell is placed in a hypertonic solution, it becomes:",
    options: ["Plasmolysed", "Turgid", "Flaccid", "Lysed"],
    correctIndex: 0,
    explanation: "In a hypertonic solution, water moves out of the cell by osmosis, causing the cell membrane to pull away from the cell wall (plasmolysis).",
    difficulty: "medium",
  },
  {
    id: qid("biology", 2022, 1, 12),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Nervous System",
    question: "The part of the brain that controls balance and coordination is the:",
    options: ["Cerebellum", "Cerebrum", "Medulla oblongata", "Hypothalamus"],
    correctIndex: 0,
    explanation: "The cerebellum coordinates voluntary movements, balance, and posture.",
    difficulty: "medium",
  },
  {
    id: qid("biology", 2022, 1, 13),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Ecology",
    question: "The conversion of atmospheric nitrogen to nitrates by bacteria is called:",
    options: ["Nitrogen fixation", "Denitrification", "Nitrification", "Ammonification"],
    correctIndex: 0,
    explanation: "Nitrogen fixation is the process by which nitrogen-fixing bacteria (e.g., Rhizobium) convert N₂ into ammonia/nitrates.",
    difficulty: "medium",
  },
  {
    id: qid("biology", 2022, 1, 14),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Genetics",
    question: "DNA stands for:",
    options: [
      "Deoxyribonucleic acid",
      "Diribonucleic acid",
      "Deoxyribonitric acid",
      "Dinucleotide acid",
    ],
    correctIndex: 0,
    explanation: "DNA (Deoxyribonucleic acid) is the molecule that carries genetic information in all living organisms.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 15),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Nutrition",
    question: "Which vitamin deficiency causes scurvy?",
    options: ["Vitamin C", "Vitamin A", "Vitamin D", "Vitamin B12"],
    correctIndex: 0,
    explanation: "Scurvy is caused by deficiency of vitamin C (ascorbic acid), leading to bleeding gums and poor wound healing.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 16),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Classification",
    question: "The binomial naming system was introduced by:",
    options: ["Carolus Linnaeus", "Charles Darwin", "Gregor Mendel", "Robert Koch"],
    correctIndex: 0,
    explanation: "Carolus Linnaeus developed the binomial nomenclature system, giving organisms two-part Latin names (genus + species).",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 17),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Hormones",
    question: "Insulin is produced by the:",
    options: ["Pancreas", "Liver", "Thyroid gland", "Adrenal gland"],
    correctIndex: 0,
    explanation: "Insulin is produced by the beta cells of the islets of Langerhans in the pancreas to regulate blood sugar.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 18),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Disease",
    question: "Malaria is transmitted by the bite of an infected female:",
    options: ["Anopheles mosquito", "Aedes mosquito", "Culex mosquito", "Tsetse fly"],
    correctIndex: 0,
    explanation: "The female Anopheles mosquito transmits Plasmodium parasites that cause malaria when it bites humans.",
    difficulty: "easy",
  },
  {
    id: qid("biology", 2022, 1, 19),
    subject: "biology",
    year: 2022,
    paper: 1,
    topic: "Circulatory System",
    question: "Which blood vessel carries oxygenated blood from the lungs to the heart?",
    options: ["Pulmonary vein", "Pulmonary artery", "Aorta", "Vena cava"],
    correctIndex: 0,
    explanation: "The pulmonary vein carries oxygenated blood from the lungs back to the left atrium of the heart.",
    difficulty: "medium",
  },
];

// ---------------------------------------------------------------------------
// MATHEMATICS  2021  Paper 1 (Objective)
// ---------------------------------------------------------------------------
const math2021P1: PastQuestion[] = [
  {
    id: qid("math", 2021, 1, 0),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Number Bases",
    question: "Convert 1A₁₆ to base 10.",
    options: ["26", "16", "10", "32"],
    correctIndex: 0,
    explanation: "1A₁₆ = 1×16 + 10×1 = 16 + 10 = 26.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2021, 1, 1),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Algebra",
    question: "If 2x + 3 = 15, find x.",
    options: ["6", "9", "3", "12"],
    correctIndex: 0,
    explanation: "2x + 3 = 15 → 2x = 12 → x = 6.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 2),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Logarithms",
    question: "Evaluate log₂ 32.",
    options: ["5", "4", "6", "3"],
    correctIndex: 0,
    explanation: "log₂ 32 = log₂ 2⁵ = 5.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 3),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Quadratic Equations",
    question: "Find the sum of roots of 2x² − 6x + 4 = 0.",
    options: ["3", "2", "−3", "6"],
    correctIndex: 0,
    explanation: "For ax² + bx + c = 0, sum of roots = −b/a = −(−6)/2 = 3.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2021, 1, 4),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Trigonometry",
    question: "What is the value of cos 60°?",
    options: ["0.5", "1", "0.866", "0"],
    correctIndex: 0,
    explanation: "cos 60° = 1/2 = 0.5. This is a standard trigonometric value.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 5),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Statistics",
    question: "Find the median of: 2, 5, 1, 8, 3.",
    options: ["3", "5", "2", "4"],
    correctIndex: 0,
    explanation: "Arranged in order: 1, 2, 3, 5, 8. The middle value (3rd) is 3.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 6),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Probability",
    question: "Two fair dice are thrown. What is the probability that the sum is 7?",
    options: ["1/6", "1/12", "7/36", "1/3"],
    correctIndex: 0,
    explanation: "Favourable outcomes: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6. Total = 36. P = 6/36 = 1/6.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2021, 1, 7),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Mensuration",
    question: "Find the volume of a cylinder with radius 7 cm and height 10 cm. (π = 22/7)",
    options: ["1540 cm³", "440 cm³", "770 cm³", "3080 cm³"],
    correctIndex: 0,
    explanation: "V = πr²h = (22/7) × 7² × 10 = (22/7) × 49 × 10 = 1540 cm³.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2021, 1, 8),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Sets",
    question: "If A = {1, 2, 3} and B = {2, 3, 4}, find A ∪ B.",
    options: ["{1, 2, 3, 4}", "{2, 3}", "{1, 4}", "{1, 2, 3, 4, 5}"],
    correctIndex: 0,
    explanation: "A ∪ B = all elements in A or B = {1, 2, 3, 4}.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 9),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Sequences",
    question: "Find the sum of the first 5 terms of the GP: 3, 6, 12, …",
    options: ["93", "45", "63", "48"],
    correctIndex: 0,
    explanation: "a = 3, r = 2, n = 5. S₅ = a(rⁿ − 1)/(r − 1) = 3(32 − 1)/1 = 93.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2021, 1, 10),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Coordinate Geometry",
    question: "Find the midpoint of (2, 4) and (6, 8).",
    options: ["(4, 6)", "(8, 12)", "(3, 5)", "(4, 4)"],
    correctIndex: 0,
    explanation: "Midpoint = ((2+6)/2, (4+8)/2) = (4, 6).",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 11),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Indices",
    question: "Simplify: (2³)² × 2⁻⁴.",
    options: ["4", "8", "16", "2"],
    correctIndex: 0,
    explanation: "(2³)² × 2⁻⁴ = 2⁶ × 2⁻⁴ = 2² = 4.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2021, 1, 12),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Percentages",
    question: "A television costs GH₵800. After a 15% discount, the selling price is:",
    options: ["GH₵680", "GH₵120", "GH₵700", "GH₵780"],
    correctIndex: 0,
    explanation: "Discount = 15% of 800 = 120. Selling price = 800 − 120 = GH₵680.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 13),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Variation",
    question: "If y varies inversely as x, and y = 6 when x = 2, find y when x = 3.",
    options: ["4", "9", "3", "12"],
    correctIndex: 0,
    explanation: "y = k/x → 6 = k/2 → k = 12. When x = 3, y = 12/3 = 4.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2021, 1, 14),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Matrices",
    question: "If P = [[1, 2], [3, 4]] and Q = [[5, 6], [7, 8]], find P + Q.",
    options: ["[[6, 8], [10, 12]]", "[[4, 4], [4, 4]]", "[[5, 12], [21, 32]]", "[[6, 6], [10, 10]]"],
    correctIndex: 0,
    explanation: "P + Q: add corresponding elements = [[1+5, 2+6], [3+7, 4+8]] = [[6, 8], [10, 12]].",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 15),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Geometry",
    question: "Two angles of a triangle are 45° and 70°. Find the third angle.",
    options: ["65°", "55°", "75°", "115°"],
    correctIndex: 0,
    explanation: "Sum of angles in a triangle = 180°. Third angle = 180 − 45 − 70 = 65°.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 16),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Surds",
    question: "Rationalise the denominator: 1/√3.",
    options: ["√3/3", "√3", "3/√3", "1/3"],
    correctIndex: 0,
    explanation: "1/√3 × √3/√3 = √3/3.",
    difficulty: "medium",
  },
  {
    id: qid("math", 2021, 1, 17),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Simultaneous Equations",
    question: "Solve: x + y = 10 and x − y = 4.",
    options: ["x = 7, y = 3", "x = 5, y = 5", "x = 6, y = 4", "x = 8, y = 2"],
    correctIndex: 0,
    explanation: "Adding: 2x = 14 → x = 7. Substituting: y = 10 − 7 = 3.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 18),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Fractions",
    question: "Simplify: (2/3 + 1/4) × 12.",
    options: ["11", "12", "8", "10"],
    correctIndex: 0,
    explanation: "2/3 + 1/4 = 8/12 + 3/12 = 11/12. Then 11/12 × 12 = 11.",
    difficulty: "easy",
  },
  {
    id: qid("math", 2021, 1, 19),
    subject: "math",
    year: 2021,
    paper: 1,
    topic: "Inequalities",
    question: "Solve: −2 ≤ 3x + 1 < 7.",
    options: ["−1 ≤ x < 2", "0 ≤ x < 3", "−1 < x ≤ 2", "−3 ≤ x < 6"],
    correctIndex: 0,
    explanation: "−2 ≤ 3x + 1 < 7 → −3 ≤ 3x < 6 → −1 ≤ x < 2.",
    difficulty: "medium",
  },
];

// ---------------------------------------------------------------------------
// Assemble Interactive Papers
// ---------------------------------------------------------------------------
export const interactivePapers: InteractivePaper[] = [
  {
    id: "math-2022-p1",
    subject: "math",
    year: 2022,
    paper: 1,
    title: "WASSCE Mathematics 2022 — Paper 1 (Objective)",
    durationMinutes: 60,
    questions: math2022P1,
  },
  {
    id: "math-2021-p1",
    subject: "math",
    year: 2021,
    paper: 1,
    title: "WASSCE Mathematics 2021 — Paper 1 (Objective)",
    durationMinutes: 60,
    questions: math2021P1,
  },
  {
    id: "physics-2022-p1",
    subject: "physics",
    year: 2022,
    paper: 1,
    title: "WASSCE Physics 2022 — Paper 1 (Objective)",
    durationMinutes: 60,
    questions: physics2022P1,
  },
  {
    id: "chemistry-2022-p1",
    subject: "chemistry",
    year: 2022,
    paper: 1,
    title: "WASSCE Chemistry 2022 — Paper 1 (Objective)",
    durationMinutes: 60,
    questions: chemistry2022P1,
  },
  {
    id: "biology-2022-p1",
    subject: "biology",
    year: 2022,
    paper: 1,
    title: "WASSCE Biology 2022 — Paper 1 (Objective)",
    durationMinutes: 60,
    questions: biology2022P1,
  },
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

export const getAvailableSubjects = (): string[] =>
  Array.from(new Set(interactivePapers.map((p) => p.subject))).sort();

export const getAvailableYears = (subject?: string): number[] =>
  Array.from(
    new Set(
      interactivePapers
        .filter((p) => !subject || p.subject === subject)
        .map((p) => p.year),
    ),
  ).sort((a, b) => b - a);

export const getAvailablePapers = (subject: string, year: number): InteractivePaper[] =>
  interactivePapers.filter((p) => p.subject === subject && p.year === year);

export const getPaperById = (id: string): InteractivePaper | undefined =>
  interactivePapers.find((p) => p.id === id);

// ---------------------------------------------------------------------------
// Question-level queries (used by Study Planner)
// ---------------------------------------------------------------------------

export const getAllQuestions = (): PastQuestion[] =>
  interactivePapers.flatMap((p) => p.questions);

export const getQuestionsByIds = (ids: string[]): PastQuestion[] => {
  const idSet = new Set(ids);
  return getAllQuestions().filter((q) => idSet.has(q.id));
};

export const getQuestionsBySubject = (subject: string): PastQuestion[] =>
  getAllQuestions().filter((q) => q.subject === subject);

export const getQuestionsByTopic = (subject: string, topic: string): PastQuestion[] =>
  getAllQuestions().filter((q) => q.subject === subject && q.topic === topic);

export const getTopicsForSubject = (subject: string): string[] =>
  Array.from(new Set(getQuestionsBySubject(subject).map((q) => q.topic))).sort();
